from typing import Protocol


class EnvironmentLifecycle(Protocol):
    """Common lifecycle contract implemented by every Environment Bundle."""

    def initialize(self) -> None: ...
    def connect(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def restart(self) -> None: ...
    def shutdown(self) -> None: ...
